project:
  type: website
  output-dir: docs

    
execute:
  freeze: true

website:
  title: "Vertikal Willis"
  site-url: https://vertikalwil.github.io/
  description: Personal website, portfolio and blog


  navbar:

    title: "VERTIKAL W.<span class='icon-line'></span>"
    right:
      - text: about
        href: about.qmd
      - text: portfolios
        href: posts.qmd
      - text: tutorials
        href: tutorial.qmd

  favicon: images/logo.png
 
format:
  html:
    theme: assets/ek-theme-dark.scss
    css: assets/ek-styles.css
    code-block-border-left: true
    highlight-style: assets/ek-dark.theme
    smooth-scroll: true
    link-external-newwindow: true
    
editor: source




