<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="testtttt">
<meta name="dcterms.date" content="2023-08-03">

<title>Ella Kaye - blog ketiga</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7G8FLLRS4M"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-7G8FLLRS4M', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js" crossorigin="anonymous"></script>


<link rel="stylesheet" href="assets/ek-styles.css">
<meta property="og:title" content="Ella Kaye - blog ketiga">
<meta property="og:image" content="https://ellakaye.co.uk/posts/post-ketiga/index_files/figure-html/cell-27-output-1.png">
<meta property="og:site-name" content="Ella Kaye">
<meta property="og:image:height" content="1186">
<meta property="og:image:width" content="2960">
<meta property="og:locale" content="en-GB">
<meta name="twitter:title" content="Ella Kaye">
<meta name="twitter:description" content="The personal website of Ella Kaye">
<meta name="twitter:image" content="https://ellakaye.co.uk/posts/post-ketiga/images/logo.png">
<meta name="twitter:creator" content="@ellamkaye">
<meta name="twitter:site" content="@ellamkaye">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ELLA<span class="icon-line"></span>KAYE</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">about</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.qmd" rel="" target="">
 <span class="menu-text">posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../talks.qmd" rel="" target="">
 <span class="menu-text">talks</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../packages.qmd" rel="" target="">
 <span class="menu-text">packages</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../community.qmd" rel="" target="">
 <span class="menu-text">community</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contact.qmd" rel="" target="">
 <span class="menu-text">contact</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Table Of Contents</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">news</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>testtttt </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 3, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="final-project.ipynb.html"><i class="bi bi-journal-code"></i>final-project.ipynb</a></li></ul></div></div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="tutorial" class="level2">
<h2 class="anchored" data-anchor-id="tutorial">Tutorial</h2>
<hr>
<div class="quarto-embed-nb-cell">
<blockquote class="blockquote">
<p>• Introduction <br> • Data Introduction <br> • Data Preparation (Import libraries, data cleaning &amp; data wrangling)<br> • Basic exploratory data analysis <br> &nbsp;&nbsp;&nbsp; * Descriptive statistic <br> &nbsp;&nbsp;&nbsp; * Univariate analysis <br> &nbsp;&nbsp;&nbsp; * Multivariate analysis <br> • Deep exploratory data analysis <br> &nbsp;&nbsp;&nbsp; * Services and internet services analysis <br> &nbsp;&nbsp;&nbsp; * Monthly charges analysis <br> &nbsp;&nbsp;&nbsp; * Customer analysis <br> &nbsp;&nbsp;&nbsp; * Benefits analysis <br> &nbsp;&nbsp;&nbsp; * Churn analysis <br> • Modelling<br> &nbsp;&nbsp;&nbsp; * Features selection and encoding <br> &nbsp;&nbsp;&nbsp; * Splits data and define custom metrics <br> &nbsp;&nbsp;&nbsp; * Model building combination 1 <br> &nbsp;&nbsp;&nbsp; * Model building combination 2 <br> &nbsp;&nbsp;&nbsp; * Model building combination 3 <br><br>
• Model interpretation<br> &nbsp;&nbsp;&nbsp; * PDP and ICE plots <br> &nbsp;&nbsp;&nbsp; * Checking prediction’s confidence using confidence interval <br></p>
</blockquote>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<hr>
<blockquote class="blockquote">
<p>This project is a final project created as one of the requirements to pass the Dibimbing Data Science Bootcamp. The dataset I used is the telco customer churn dataset, which is popular and commonly used for practice. I chose this dataset because it has numerous columns and it represents a ‘real-life’ dataset from an actual telco company. The problem faced by the company is customer churn, which results in financial loss. The solution involves providing prospects and promotions to potential churned customers, but this action also incurs costs for the company. Therefore, accurately targeting the churned customers is crucial. Based on this problem, I set two main goals:<br><br> 1.Look for useful information, insights, and patterns by performing exploratory data analysis.<br> 2.Create an ML model that best fits the company’s goal of reducing losses.</p>
</blockquote>
</section>
<section id="data-introduction" class="level1">
<h1>Data Introduction</h1>
<hr>
<blockquote class="blockquote">
<p>This dataset contain informations about customers that churn and not churned in a telco company. Below is the column informations:<br> 1.customerID = customer unique ID.<br> 2.gender = customer gender (M/F).<br> 3.SeniorCitizen = old / young customer.<br> 4.Partner = either a customer has partners or not.<br> 5.Dependents = either a customer has dependents or not.<br> 6.tenure = how long the customer subscribed (in month).<br> 7.MultipleLines = either a customer using multiple lines or not (phone lines).<br> 8.InternetService = either a customer using InternetService lines or not.<br> 9.OnlineSecurity = either a customer has OnlineSecurity or not.<br> 10.OnlineBackup = either a customer has OnlineBackup or not.<br> 11.DeviceProtection = either a customer has DeviceProtection or not.<br> 12.TechSupport = either a customer has TechSupport or not.<br> 13.StreamingTV = either a customer has StreamingTV or not.<br> 14.StreamingMovies = either a customer has StreamingMovie or not.<br> 15.Contract = types of contract.<br> 16.PaperlessBilling = either a customer has PaperlessBilling or not.<br> 17.PaymentMethod = types of the payment method.<br> 18.MonthlyCharges = how much charges per month.<br> 19.TotalCharges = total charges of all time.<br> 20.Churn = either a customer churn or not.<br> 21.Hobby = customer hobby.<br><br></p>
</blockquote>
<section id="data-preparation-import-libraries-data-cleaning-data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation-import-libraries-data-cleaning-data-wrangling">Data Preparation (Import libraries, data cleaning &amp; data wrangling)</h2>
<hr>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:24,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359104,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="2366b164-8324-46c7-b7df-c285928418ef" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">customerID</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">SeniorCitizen</th>
<th data-quarto-table-cell-role="th">Partner</th>
<th data-quarto-table-cell-role="th">Dependents</th>
<th data-quarto-table-cell-role="th">tenure</th>
<th data-quarto-table-cell-role="th">PhoneService</th>
<th data-quarto-table-cell-role="th">MultipleLines</th>
<th data-quarto-table-cell-role="th">InternetService</th>
<th data-quarto-table-cell-role="th">OnlineSecurity</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">TechSupport</th>
<th data-quarto-table-cell-role="th">StreamingTV</th>
<th data-quarto-table-cell-role="th">StreamingMovies</th>
<th data-quarto-table-cell-role="th">Contract</th>
<th data-quarto-table-cell-role="th">PaperlessBilling</th>
<th data-quarto-table-cell-role="th">PaymentMethod</th>
<th data-quarto-table-cell-role="th">MonthlyCharges</th>
<th data-quarto-table-cell-role="th">TotalCharges</th>
<th data-quarto-table-cell-role="th">Churn</th>
<th data-quarto-table-cell-role="th">Hobby</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>7590-VHVEG</td>
<td>Female</td>
<td>0</td>
<td>Yes</td>
<td>No</td>
<td>135</td>
<td>No</td>
<td>No phone service</td>
<td>DSL</td>
<td>No</td>
<td>...</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>Month-to-month</td>
<td>Yes</td>
<td>Electronic check</td>
<td>29.85</td>
<td>29.85</td>
<td>No</td>
<td>Swimming</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>5575-GNVDE</td>
<td>Male</td>
<td>0</td>
<td>No</td>
<td>No</td>
<td>34</td>
<td>Yes</td>
<td>No</td>
<td>DSL</td>
<td>Yes</td>
<td>...</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>One year</td>
<td>No</td>
<td>Mailed check</td>
<td>56.95</td>
<td>1889.5</td>
<td>No</td>
<td>Running</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3668-QPYBK</td>
<td>Male</td>
<td>0</td>
<td>No</td>
<td>No</td>
<td>140</td>
<td>Yes</td>
<td>No</td>
<td>DSL</td>
<td>Yes</td>
<td>...</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>Month-to-month</td>
<td>Yes</td>
<td>Mailed check</td>
<td>53.85</td>
<td>7560</td>
<td>Yes</td>
<td>Hiking</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>7795-CFOCW</td>
<td>Male</td>
<td>0</td>
<td>No</td>
<td>No</td>
<td>136</td>
<td>No</td>
<td>No phone service</td>
<td>DSL</td>
<td>Yes</td>
<td>...</td>
<td>Yes</td>
<td>No</td>
<td>No</td>
<td>One year</td>
<td>No</td>
<td>Bank transfer (automatic)</td>
<td>42.45</td>
<td>1840.75</td>
<td>No</td>
<td>Swimming</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>9237-HQITU</td>
<td>Female</td>
<td>0</td>
<td>No</td>
<td>No</td>
<td>2</td>
<td>Yes</td>
<td>No</td>
<td>Fiber optic</td>
<td>No</td>
<td>...</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>Month-to-month</td>
<td>Yes</td>
<td>Electronic check</td>
<td>70.70</td>
<td>151.65</td>
<td>Yes</td>
<td>Running</td>
</tr>
</tbody>
</table>

<p>5 rows × 22 columns</p>
</div>
</div>
</div>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:23,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359105,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="3767453b-34e8-4162-c1ae-4b31e4af10ad" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  6627 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          6798 non-null   object 
 16  PaperlessBilling  7043 non-null   object 
 17  PaymentMethod     7043 non-null   object 
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      4859 non-null   object 
 20  Churn             7043 non-null   object 
 21  Hobby             4201 non-null   object 
dtypes: float64(1), int64(2), object(19)
memory usage: 1.2+ MB</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>There are 4 columns with missing values which are DeviceProtection, Contract, TotalCharges and Hobby.</p>
</blockquote>
<div class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Missing value of column DeviceProtection (%) : 5.91
Missing value of column Contract (%) : 3.48
Missing value of column TotalCharges (%) : 31.01
Missing value of column Hobby (%) : 40.35</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Here I impute DeviceProtection and Contract with univariate imputation by value proportion for the following reasons:<br> 1.The missing values is not that much (&lt;10%).<br> 2.The columns don’t have any relationship with other columns so that multivariate imputation is not possible.<br> 3.Using proportion is more precise in this case rather than use ‘mode’.</p>
</blockquote>
<blockquote class="blockquote">
<p>Reasons to delete:<br> 1.Missing values is too many.<br> 2.By business context, Hobby doesn’t give enough useful informations.<br> 3.Cannot be imputed by multivariate imputation.<br></p>
</blockquote>
<blockquote class="blockquote">
<p>Even this column has so many missing values, I decided to impute it with multivariate imputation because:<br> 1.By business context, TotalCharges is more or less tenure * MonthlyCharges.<br> 2.So even the missing values are high, it can still be imputed with a strong justification.<br></p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:20,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359105,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="8424ee92-08be-47c3-b65c-50731eb84dc7" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  
Unable to convert to float with this value :  </code></pre>
</div>
</div>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:18,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359105,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="cf0d5a83-8763-4971-8f97-54265ea580b8" data-execution_count="10">
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">customerID</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">SeniorCitizen</th>
<th data-quarto-table-cell-role="th">Partner</th>
<th data-quarto-table-cell-role="th">Dependents</th>
<th data-quarto-table-cell-role="th">tenure</th>
<th data-quarto-table-cell-role="th">PhoneService</th>
<th data-quarto-table-cell-role="th">MultipleLines</th>
<th data-quarto-table-cell-role="th">InternetService</th>
<th data-quarto-table-cell-role="th">OnlineSecurity</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">DeviceProtection</th>
<th data-quarto-table-cell-role="th">TechSupport</th>
<th data-quarto-table-cell-role="th">StreamingTV</th>
<th data-quarto-table-cell-role="th">StreamingMovies</th>
<th data-quarto-table-cell-role="th">Contract</th>
<th data-quarto-table-cell-role="th">PaperlessBilling</th>
<th data-quarto-table-cell-role="th">PaymentMethod</th>
<th data-quarto-table-cell-role="th">MonthlyCharges</th>
<th data-quarto-table-cell-role="th">TotalCharges</th>
<th data-quarto-table-cell-role="th">Churn</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">488</td>
<td>4472-LVYGI</td>
<td>Female</td>
<td>0</td>
<td>Yes</td>
<td>Yes</td>
<td>0</td>
<td>No</td>
<td>No phone service</td>
<td>DSL</td>
<td>Yes</td>
<td>...</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>No</td>
<td>Month-to-month</td>
<td>Yes</td>
<td>Bank transfer (automatic)</td>
<td>52.55</td>
<td></td>
<td>No</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">753</td>
<td>3115-CZMZD</td>
<td>Male</td>
<td>0</td>
<td>No</td>
<td>Yes</td>
<td>0</td>
<td>Yes</td>
<td>No</td>
<td>No</td>
<td>No internet service</td>
<td>...</td>
<td>No internet service</td>
<td>No internet service</td>
<td>No internet service</td>
<td>No internet service</td>
<td>Two year</td>
<td>No</td>
<td>Mailed check</td>
<td>20.25</td>
<td></td>
<td>No</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">936</td>
<td>5709-LVOEQ</td>
<td>Female</td>
<td>0</td>
<td>Yes</td>
<td>Yes</td>
<td>0</td>
<td>Yes</td>
<td>No</td>
<td>DSL</td>
<td>Yes</td>
<td>...</td>
<td>No</td>
<td>No</td>
<td>Yes</td>
<td>Yes</td>
<td>Two year</td>
<td>No</td>
<td>Mailed check</td>
<td>80.85</td>
<td></td>
<td>No</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1082</td>
<td>4367-NUYAO</td>
<td>Male</td>
<td>0</td>
<td>Yes</td>
<td>Yes</td>
<td>0</td>
<td>Yes</td>
<td>Yes</td>
<td>No</td>
<td>No internet service</td>
<td>...</td>
<td>Yes</td>
<td>No internet service</td>
<td>No internet service</td>
<td>No internet service</td>
<td>Two year</td>
<td>No</td>
<td>Mailed check</td>
<td>25.75</td>
<td></td>
<td>No</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1334</td>
<td>1768-ZAIFU</td>
<td>Female</td>
<td>1</td>
<td>No</td>
<td>No</td>
<td>0</td>
<td>No</td>
<td>No phone service</td>
<td>DSL</td>
<td>No</td>
<td>...</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>Month-to-month</td>
<td>Yes</td>
<td>Electronic check</td>
<td>25.20</td>
<td></td>
<td>Yes</td>
</tr>
</tbody>
</table>

<p>5 rows × 21 columns</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>When the tenure value is 0, the TotalCharges value is empty (‘space’). This is because customers who have just joined (less than a month) have not been charged yet, resulting in a TotalCharges value of 0. Since there are only 12 rows with this condition, I will delete them.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:18,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359106,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="b764d9bd-c07a-4372-a29d-ea323b83ef1e" data-execution_count="12">
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>True</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>New features explanation: <br> 1.Services = Combined values of PhoneService and InternetService.<br> 2.TotalBenefits = Sum of benefits taken on OnlineSecurity until StreamingMovies.</p>
</blockquote>
<blockquote class="blockquote">
<p>Change numerical value to strings for simpler and consistent analysis.</p>
</blockquote>
<blockquote class="blockquote">
<p>Here, I have created a new column called TotalChargesDiff to check the differences (%) between the actual TotalCharges value (from the dataset) and the calculated TotalCharges value (obtained by multiplying tenure with MonthlyCharges). If the difference is above 40%, I will consider those rows as invalid because the values of tenure and MonthlyCharges cannot be trusted.</p>
</blockquote>
<div class="cell" data-execution_count="18">
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>0       13400.000
5        1357.404
18        788.048
19        330.214
3         213.633
128        73.511
47         72.615
4631       64.286
5802       63.380
20         58.263
Name: TotalChargesDiff, dtype: float64</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>You can observe that some data points have a TotalChargesDiff that reaches hundreds or even thousands.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:15,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359107,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="6fd750ef-03a5-45c6-8b8f-b5be98c30aec" data-execution_count="21">
<div class="cell-output cell-output-stdout">
<pre><code>TotalNumericalData = 4
TotalCategoricalData = 18
Numerical = ['tenure', 'MonthlyCharges', 'TotalCharges', 'TotalBenefits']
Categorical = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn', 'Services']</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Show numerical and categorical columns</p>
</blockquote>
</section>
<section id="basic-exploratory-data-analysis." class="level2">
<h2 class="anchored" data-anchor-id="basic-exploratory-data-analysis.">Basic Exploratory Data Analysis.</h2>
<hr>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:13,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359107,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="3189de7c-197e-4764-db1b-f9bfe6d65df0" data-execution_count="23">
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">tenure</th>
<th data-quarto-table-cell-role="th">MonthlyCharges</th>
<th data-quarto-table-cell-role="th">TotalCharges</th>
<th data-quarto-table-cell-role="th">TotalBenefits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>7012.000000</td>
<td>7012.000000</td>
<td>7012.000000</td>
<td>7012.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>32.506560</td>
<td>64.732760</td>
<td>2286.410207</td>
<td>2.041358</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>24.564234</td>
<td>30.109753</td>
<td>2265.759401</td>
<td>1.835792</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1.000000</td>
<td>12.000000</td>
<td>13.500000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>9.000000</td>
<td>35.450000</td>
<td>402.437500</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>29.000000</td>
<td>70.300000</td>
<td>1397.250000</td>
<td>2.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>56.000000</td>
<td>89.850000</td>
<td>3784.125000</td>
<td>3.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>140.000000</td>
<td>118.750000</td>
<td>8684.800000</td>
<td>6.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<blockquote class="blockquote">
<p>1.All columns seems to have a normal min-max values. Nothing weird here.<br> 2.Average tenure is about 30 months which is pretty low.<br> 3.Average MonthlyCharge is about 65-70 USD which is pretty good.<br> 4.Out of 6 benefits available, the average taken by customer is around 2, which is pretty low.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:14,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644359108,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="a0cb4619-90ed-4ff8-9888-2a3dd67a0abe" data-execution_count="24">
<div class="cell-output cell-output-display" data-execution_count="24">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">SeniorCitizen</th>
<th data-quarto-table-cell-role="th">Partner</th>
<th data-quarto-table-cell-role="th">Dependents</th>
<th data-quarto-table-cell-role="th">PhoneService</th>
<th data-quarto-table-cell-role="th">MultipleLines</th>
<th data-quarto-table-cell-role="th">InternetService</th>
<th data-quarto-table-cell-role="th">OnlineSecurity</th>
<th data-quarto-table-cell-role="th">OnlineBackup</th>
<th data-quarto-table-cell-role="th">DeviceProtection</th>
<th data-quarto-table-cell-role="th">TechSupport</th>
<th data-quarto-table-cell-role="th">StreamingTV</th>
<th data-quarto-table-cell-role="th">StreamingMovies</th>
<th data-quarto-table-cell-role="th">Contract</th>
<th data-quarto-table-cell-role="th">PaperlessBilling</th>
<th data-quarto-table-cell-role="th">PaymentMethod</th>
<th data-quarto-table-cell-role="th">Churn</th>
<th data-quarto-table-cell-role="th">Services</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
<td>7012</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>2</td>
<td>4</td>
<td>2</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>Male</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>Yes</td>
<td>No</td>
<td>Fiber optic</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>Month-to-month</td>
<td>Yes</td>
<td>Electronic check</td>
<td>No</td>
<td>Both</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>3542</td>
<td>5874</td>
<td>3624</td>
<td>4920</td>
<td>6336</td>
<td>3372</td>
<td>3087</td>
<td>3486</td>
<td>3075</td>
<td>3072</td>
<td>3459</td>
<td>2798</td>
<td>2769</td>
<td>3851</td>
<td>4155</td>
<td>2354</td>
<td>5155</td>
<td>4821</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<blockquote class="blockquote">
<p>1.Male and Female has the same proportion.<br> 2.Most of customers is non SeniorCitizen with no Partner and No Dependents.<br> 3.Favorite InternetService is Fiber optic.<br> 4.Majority of customers is subscribed with ‘Month-to-month’ Contract.<br> 5.5155 out of 7012 is non-Churn customers which make this dataset is imbalanced.<br> 6.All these columns have low cardiality values.</p>
</blockquote>
<div class="cell" data-execution_count="25">
<div class="cell-output cell-output-stdout">
<pre><code>Value counts for column gender:
Male      3542
Female    3470
Name: gender, dtype: int64
------------------------------


Value counts for column SeniorCitizen:
No     5874
Yes    1138
Name: SeniorCitizen, dtype: int64
------------------------------


Value counts for column Partner:
No     3624
Yes    3388
Name: Partner, dtype: int64
------------------------------


Value counts for column Dependents:
No     4920
Yes    2092
Name: Dependents, dtype: int64
------------------------------


Value counts for column PhoneService:
Yes    6336
No      676
Name: PhoneService, dtype: int64
------------------------------


Value counts for column MultipleLines:
No                  3372
Yes                 2964
No phone service     676
Name: MultipleLines, dtype: int64
------------------------------


Value counts for column InternetService:
Fiber optic    3087
DSL            2410
No             1515
Name: InternetService, dtype: int64
------------------------------


Value counts for column OnlineSecurity:
No                     3486
Yes                    2011
No internet service    1515
Name: OnlineSecurity, dtype: int64
------------------------------


Value counts for column OnlineBackup:
No                     3075
Yes                    2422
No internet service    1515
Name: OnlineBackup, dtype: int64
------------------------------


Value counts for column DeviceProtection:
No                     3072
Yes                    2416
No internet service    1524
Name: DeviceProtection, dtype: int64
------------------------------


Value counts for column TechSupport:
No                     3459
Yes                    2038
No internet service    1515
Name: TechSupport, dtype: int64
------------------------------


Value counts for column StreamingTV:
No                     2798
Yes                    2699
No internet service    1515
Name: StreamingTV, dtype: int64
------------------------------


Value counts for column StreamingMovies:
No                     2769
Yes                    2728
No internet service    1515
Name: StreamingMovies, dtype: int64
------------------------------


Value counts for column Contract:
Month-to-month    3851
Two year          1697
One year          1464
Name: Contract, dtype: int64
------------------------------


Value counts for column PaperlessBilling:
Yes    4155
No     2857
Name: PaperlessBilling, dtype: int64
------------------------------


Value counts for column PaymentMethod:
Electronic check             2354
Mailed check                 1599
Bank transfer (automatic)    1539
Credit card (automatic)      1520
Name: PaymentMethod, dtype: int64
------------------------------


Value counts for column Churn:
No     5155
Yes    1857
Name: Churn, dtype: int64
------------------------------


Value counts for column Services:
Both             4821
Phone Only       1515
Internet Only     676
Name: Services, dtype: int64
------------------------------

</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Show all value counts for each categorical columns.</p>
</blockquote>
</section>
<section id="univariate-analysis" class="level3">
<h3 class="anchored" data-anchor-id="univariate-analysis">Univariate Analysis</h3>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:4816,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644363913,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="170c154e-b2f7-4f3c-8eaa-b7dba683bd5c" data-execution_count="26">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-27-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Will drop outlier in tenure.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:13,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644363913,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="a547964b-2068-41fa-beb9-f5d5f4cdd30a" data-execution_count="28">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-29-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Above plots are distribution plots on all numerical columns.<br> 1.tenure and MonthlyCharges have a ‘U-shaped’ distribution.<br> 2.TotalCharges has a positive-skew distribution.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:2927,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644366827,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="d3c33666-387d-4a3b-b2ff-3996eb789f6d" data-execution_count="29">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-30-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Here I count plotted all categorical columns.</p>
</blockquote>
</section>
<section id="multivariate-analysis" class="level3">
<h3 class="anchored" data-anchor-id="multivariate-analysis">Multivariate Analysis</h3>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:2131,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644368955,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="a3140ce1-14b9-452a-e701-b518d094bcf2" data-execution_count="30">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-31-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>I added Churn count into the categorical plots.<br> 1.You can see for column Gender, the values and Churn count is pretty equal which make this column will have a very low predictive power.<br> 2.For InternetService, fiber optic has way higher in churn probability compare to DSL.<br> 3.Same ways also applied on Month-to-month Contract and Electronic-check PaymentMethod.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:4080,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644373032,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="4fb0d4d8-157a-41e3-814d-368da499e070" data-execution_count="31">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-32-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Let’s also compare Churn distribution on numerical columns. Customers tend to churn when the tenure is low and not churn when the MonthlyCharges is very low. I will do further analysis about these columns later.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:7,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644373032,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="5a370df8-4d5b-432b-cc9c-ed8e651a803f" data-execution_count="33">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-34-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Correlation!<br> 1.TotalCharges and tenure have a high positive correlation (causation : the longer the customers subscribed, the more they paid).<br> 2.TotalBenefits also has a strong correlation with MonthlyCharges and TotalCharges (causation : more benefits taken also make the MonthlyCharges higher).<br> Note : Correlation doesn’t indicate causation. Understanding the specific context, industry knowledge, and conducting further analysis or experiments can help determine if there is a causal relationship between the variables or if other factors are influencing the observed correlations.</p>
</blockquote>
</section>
</section>
<section id="deep-dive-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="deep-dive-exploratory-data-analysis">Deep-Dive Exploratory Data Analysis</h2>
<hr>
<section id="services-internetservice-analysis" class="level3">
<h3 class="anchored" data-anchor-id="services-internetservice-analysis">Services &amp; InternetService analysis</h3>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:15,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644459390,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="3b5dfc76-98ae-43f3-e95c-024c8834ebb8" data-execution_count="35">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-36-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>It is observed that customers tend to prefer Fiber optic over DSL for ‘phone &amp; internet service’. However, when considering ‘internet service only’ without phone, there is no option for Fiber optic available. This suggests that in order to utilize Fiber optic, a phone connection (or phone service) is required.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:1333,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460709,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="c146769d-3b88-4454-bf06-7a0494efd1d7" data-execution_count="36">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-37-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Customers that used ‘Both’ services and InternetService fiber optic tends to churn more.</p>
</blockquote>
</section>
<section id="monthlycharges-analysis" class="level3">
<h3 class="anchored" data-anchor-id="monthlycharges-analysis">MonthlyCharges analysis</h3>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:26,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460710,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="8117c6d1-344a-4989-ad74-87f75d24247d" data-execution_count="37">
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>InternetService
DSL            44.963824
Fiber optic    70.083186
Name: MonthlyCharges, dtype: float64</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The price of Fiber optic is higher, around 25 USD, compared to DSL. However, it’s important to keep in mind that these prices include a phone service with a single line.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:25,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460710,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="80e9644f-1a90-4177-e68b-4374a785d47d" data-execution_count="38">
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>MultipleLines
No     19.953819
Yes    24.973716
Name: MonthlyCharges, dtype: float64</code></pre>
</div>
</div>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:24,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460710,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="2499b9e2-4388-49bf-ee6c-af13edec5c38" data-execution_count="39">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-40-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>We can see that the price for a ‘phone service’ with a single line is around 20 USD, while the price for a ‘phone service’ with multiple lines is around 25 USD. This also means that the price for DSL is around 25 USD, while the price for Fiber optic is around 50 USD, which is twice as much as DSL.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:24,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460711,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="ce28b72e-2787-4f0e-925c-c76d3f9983d2" data-execution_count="40">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-41-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>At a MonthlyCharges range of approximately +- 20 USD, the ratio of non-churn customers is very high. It is known that products within this price range are typically ‘phone service only’. However, between the price range of 60 - 100 USD, the churn probability increases significantly. I am planning to conduct further analysis specifically for customers within this price range.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:22,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460711,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="e99960cb-8117-4037-e1fa-e548ef109dc3" data-execution_count="42">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-43-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Here, you can observe that as more TotalBenefits are taken, the MonthlyCharges also increase. On the left plot, you can see that there are 5 outlier data points, which will be removed later.</p>
</blockquote>
<div class="cell" data-execution_count="44">
<div class="cell-output cell-output-display" data-execution_count="44">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Benefit</th>
<th data-quarto-table-cell-role="th">MinCharges</th>
<th data-quarto-table-cell-role="th">MaxCharges</th>
<th data-quarto-table-cell-role="th">MeanCharges</th>
<th data-quarto-table-cell-role="th">MedianCharges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>OnlineSecurity</td>
<td>73.2</td>
<td>80.3</td>
<td>74.952857</td>
<td>75.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>OnlineBackup</td>
<td>72.75</td>
<td>76.65</td>
<td>74.708511</td>
<td>74.65</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>DeviceProtection</td>
<td>69.55</td>
<td>76.65</td>
<td>74.258889</td>
<td>74.8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>TechSupport</td>
<td>73.85</td>
<td>76.55</td>
<td>75.045455</td>
<td>74.7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>StreamingTV</td>
<td>77.65</td>
<td>81.9</td>
<td>79.746825</td>
<td>79.75</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>StreamingMovies</td>
<td>12.0</td>
<td>86.45</td>
<td>79.16746</td>
<td>80.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<blockquote class="blockquote">
<p>Above are the prices of benefits with Fiber optic and a single line phone connection. You can see that StreamingTV and StreamingMovies are more expensive compared to other benefits, approximately +- 5 USD.</p>
</blockquote>
<p>Now that we know the prices of every product, here’s a recap:<br></p>
<p>DSL = approximately 25 USD.<br> Fiber optic = approximately 50 USD.<br> Phone service (single line) = approximately 20 USD.<br> Phone service (multiple lines) = approximately 25 USD.<br> OnlineSecurity - TechSupport = approximately 5 USD.<br> StreamingTV - StreamingMovies = approximately 10 USD.<br></p>
<p>With this data, we can perform a simple ‘anomaly detection’ by manually calculating the MonthlyCharges and comparing them with the actual MonthlyCharges, similar to how we calculated the TotalChargesDiff above.</p>
<div class="cell" data-execution_count="47">
<div class="cell-output cell-output-display" data-execution_count="47">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MonthlyCharges</th>
<th data-quarto-table-cell-role="th">MonthlyChargesEstimationDifference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>29.00</td>
<td>296.551724</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">389</td>
<td>12.00</td>
<td>733.333333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">666</td>
<td>12.00</td>
<td>566.666667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">859</td>
<td>26.41</td>
<td>278.644453</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1439</td>
<td>18.26</td>
<td>447.645126</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2185</td>
<td>21.63</td>
<td>362.320851</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4090</td>
<td>31.26</td>
<td>219.897633</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5848</td>
<td>15.00</td>
<td>466.666667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6718</td>
<td>21.00</td>
<td>304.761905</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<blockquote class="blockquote">
<p>You can see that there are 9 rows with extreme MonthlyCharges values. These are considered as ‘anomalies’, so let’s remove them.</p>
</blockquote>
</section>
<section id="customer-analysis" class="level3">
<h3 class="anchored" data-anchor-id="customer-analysis">Customer analysis</h3>
<blockquote class="blockquote">
<p>I have created a new feature called ‘Status’. This feature is derived from the columns Partner and Dependents.<br><br> 1.If customers have both Partner and Dependents, it will be labeled as ‘Both’.<br> 2.If customers have Partner but no Dependents, it will be labeled as ‘Partner Only’.<br> 3.If customers have Dependents but no Partner, it will be labeled as ‘Dependent Only’.<br> 4.If customers have neither Partner nor Dependents, it will be labeled as ‘Single’.<br></p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:21,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460712,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="92ac2c61-a43c-49e7-a10d-bf2619ae13d4" data-execution_count="51">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-52-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Majority of customers are Single.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:21,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460712,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="bb780263-68a3-4cf7-bb4c-7cb0caf75bfb" data-execution_count="52">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-53-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Customers labeled as ‘Partner Only’ are considered the best since they have the longest tenure and the highest MonthlyCharges. The second-best group is ‘Both’, although these customers may not have MonthlyCharges as high as those in the ‘Single’ group, their tenure is almost double that of the ‘Single’ group.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:21,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460713,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="e59c631a-c7db-401b-b61b-4cb64e9cae6d" data-execution_count="53">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-54-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Single customers have the highest churn probability.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:20,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460713,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="88e0aacd-d3b0-4bf5-c098-6188aa3680c6" data-execution_count="54">
<div class="cell-output cell-output-display" data-execution_count="54">
<pre><code>No     0.837903
Yes    0.162097
Name: SeniorCitizen, dtype: float64</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The majority of customers are young people.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:21,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460714,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="a518d565-5aa8-44dc-bc45-539538aae93c" data-execution_count="56">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-57-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>For non-Senior citizens, ‘Single’ customers have the highest frequency, followed by ‘Both’. For Senior citizens, ‘Single’ is also the highest category, but the difference with ‘PartnerOnly’ is not as significant. From the plots above, we can also conclude that young people tend to have dependents more than older people.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:20,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644460715,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="0213aa2b-d477-4d53-9800-82148d57f615" data-execution_count="58">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-59-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Single and PartnerOnly customers tend to prefer entertainment benefits such as StreamingTV and StreamingMovies compared to other customers. Additionally, these customers show a lower preference for using TechSupport and OnlineSecurity.</p>
</blockquote>
</section>
<section id="benefits-analysis" class="level3">
<h3 class="anchored" data-anchor-id="benefits-analysis">Benefits analysis</h3>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:1450,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644462145,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="8c9a5f17-99b8-49f1-d489-a584a40403da" data-execution_count="59">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-60-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>The average number of TotalBenefits taken by customers is around 3, with StreamingTV and StreamingMovies being the most popular choices.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:5,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644462146,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="ca567756-56c7-422b-bc62-5957e94729b4" data-execution_count="61">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-62-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>While StreamingTV and StreamingMovies are the most favored choices, the churn probability associated with them is also the highest.</p>
</blockquote>
</section>
<section id="churn-analysis" class="level3">
<h3 class="anchored" data-anchor-id="churn-analysis">Churn analysis</h3>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:2475,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644464617,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="1c9642d7-a37f-4cfc-abc1-37fd31be306f" data-execution_count="62">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-63-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Here, I have created two areas, denoted by green and blue, both focusing on MonthlyCharges in the range of 70 - 95 USD. This price range corresponds to the highest churn probability. The green area represents customers with low tenure and is predominantly occupied by churned customers, while the blue area represents customers with high tenure and is predominantly occupied by non-churned customers.</p>
</blockquote>
<div class="cell" data-executioninfo="{&quot;elapsed&quot;:2365,&quot;status&quot;:&quot;ok&quot;,&quot;timestamp&quot;:1679644466969,&quot;user&quot;:{&quot;displayName&quot;:&quot;vertikal willis&quot;,&quot;userId&quot;:&quot;09422096490593763616&quot;},&quot;user_tz&quot;:-420}" data-outputid="041fbef0-cc28-482a-d89f-e464a718002c" data-execution_count="63">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-64-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Still on the same plot, I have added TotalBenefits and InternetService. It can be observed that in the green area, Fiber optic is the dominant InternetService with low TotalBenefits. On the other hand, the blue area is dominated by DSL with high TotalBenefits. This indicates that customers, at the same price point, tend to choose DSL with high TotalBenefits rather than Fiber optic with low TotalBenefits. Note that Fiber optic prices are doubled than DSL.</p>
</blockquote>
<p>With the observed pattern above, we can create an important new feature, which we will refer to as ‘FO_LB’ (Fiber optic_Low benefit). I will assign a value of ‘1’ to indicate that the internet service is Fiber optic and the Totalbenefits taken are less than or equal to 3. For other cases, I will assign ‘0’.</p>
</section>
</section>
<section id="modelling" class="level2">
<h2 class="anchored" data-anchor-id="modelling">Modelling</h2>
<hr>
<p>One important thing to address before we proceed is considering the types of errors to make this project as realistic as possible. Typically, there are two types of errors: false positive (FP) and false negative (FN). However, in this project, I will introduce three types of errors.<br></p>
<p>1.FP: False positive <br> 2.FN1: False negative for customers with MonthlyCharges below 95 USD <br> 3.FN2: False negative for customers with MonthlyCharges above 95 USD (VIP customers) <br> Let’s agree on the misclassification ratio, which is FP:FN1:FN2 = 1:3:5 <br></p>
<p>It’s important to note that this dataset is imbalanced, meaning there is a significant difference in the number of samples between the classes.</p>
<p>Based on these problems, we can set up our model’s parameters as follows:<br><br> 1.Hyperparameter tuning.<br> 2.Decision threshold tuning.<br> 3.Oversampling data using SMOTE.<br> 4.Applying weights to the models.<br> I will be using Random Forest, XGBoost, and Logistic Regression.</p>
<p>Metrics:<br> Custom scoring based on sample misclassification.<br> Precision.<br> Recall.<br> F1_score.<br> Once the models are evaluated using these metrics, I will interpret the best model.</p>
<section id="feature-selection-encoding" class="level3">
<h3 class="anchored" data-anchor-id="feature-selection-encoding">Feature selection &amp; encoding</h3>
<blockquote class="blockquote">
<p>I have dropped the columns from ‘Services’ to ‘Status’ as these columns were engineered features created for simpler exploratory data analysis (EDA). Additionally, I have also dropped the ‘PaperlessBilling’ and ‘PaymentMethod’ columns because, in the business context, these columns are considered irrelevant for determining customer churn since they represent optional ‘features’ for customers.</p>
</blockquote>
<blockquote class="blockquote">
<p>Here I only choose a feature that have a strong predictive power (by using feature of importances)</p>
</blockquote>
</section>
<section id="splits-data-and-define-custom-function" class="level3">
<h3 class="anchored" data-anchor-id="splits-data-and-define-custom-function">Splits data and define custom function</h3>
</section>
<section id="model-building-1-hyperparameter-tuning-threshold-tuning" class="level3">
<h3 class="anchored" data-anchor-id="model-building-1-hyperparameter-tuning-threshold-tuning">Model building 1 / Hyperparameter tuning + threshold tuning</h3>
<div class="cell" data-execution_count="82">
<div class="cell-output cell-output-display" data-execution_count="82">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">threshold</th>
<th data-quarto-table-cell-role="th">score</th>
<th data-quarto-table-cell-role="th">precision</th>
<th data-quarto-table-cell-role="th">recall</th>
<th data-quarto-table-cell-role="th">f1</th>
<th data-quarto-table-cell-role="th">params</th>
<th data-quarto-table-cell-role="th">model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.24</td>
<td>539.0</td>
<td>0.473101</td>
<td>0.828255</td>
<td>0.602216</td>
<td>{'bootstrap': True, 'max_depth': 25, 'min_samp...</td>
<td>MB1_RF</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.20</td>
<td>558.0</td>
<td>0.449190</td>
<td>0.844875</td>
<td>0.586538</td>
<td>{'colsample_bytree': 0.8, 'learning_rate': 0.0...</td>
<td>MB1_XG</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.22</td>
<td>541.0</td>
<td>0.467492</td>
<td>0.836565</td>
<td>0.599801</td>
<td>{'C': 0.1, 'max_iter': 50, 'penalty': 'l2', 's...</td>
<td>MB1_Log_Reg</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="model-building-2-hyperparameter-tuning-threshold-tuning-smote" class="level3">
<h3 class="anchored" data-anchor-id="model-building-2-hyperparameter-tuning-threshold-tuning-smote">Model building 2 / Hyperparameter tuning + threshold tuning + SMOTE</h3>
<div class="cell" data-execution_count="86">
<div class="cell-output cell-output-display" data-execution_count="86">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">threshold</th>
<th data-quarto-table-cell-role="th">score</th>
<th data-quarto-table-cell-role="th">precision</th>
<th data-quarto-table-cell-role="th">recall</th>
<th data-quarto-table-cell-role="th">f1</th>
<th data-quarto-table-cell-role="th">params</th>
<th data-quarto-table-cell-role="th">model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.42</td>
<td>557.0</td>
<td>0.454955</td>
<td>0.839335</td>
<td>0.590068</td>
<td>{'bootstrap': False, 'max_depth': 25, 'min_sam...</td>
<td>MB2_RF</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.44</td>
<td>546.0</td>
<td>0.472266</td>
<td>0.825485</td>
<td>0.600806</td>
<td>{'colsample_bytree': 1.0, 'learning_rate': 0.0...</td>
<td>MB2_XG</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.48</td>
<td>546.0</td>
<td>0.472178</td>
<td>0.822715</td>
<td>0.600000</td>
<td>{'C': 1.0, 'max_iter': 50, 'penalty': 'l2', 's...</td>
<td>MB2_Log_Reg</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="model-building-3-hyperparameter-tuning-threshold-tuning-custom-weight" class="level3">
<h3 class="anchored" data-anchor-id="model-building-3-hyperparameter-tuning-threshold-tuning-custom-weight">Model building 3 / Hyperparameter tuning + threshold tuning + custom weight</h3>
<div class="cell" data-execution_count="90">
<div class="cell-output cell-output-display" data-execution_count="90">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">threshold</th>
<th data-quarto-table-cell-role="th">score</th>
<th data-quarto-table-cell-role="th">precision</th>
<th data-quarto-table-cell-role="th">recall</th>
<th data-quarto-table-cell-role="th">f1</th>
<th data-quarto-table-cell-role="th">params</th>
<th data-quarto-table-cell-role="th">model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.48</td>
<td>549.0</td>
<td>0.456193</td>
<td>0.836565</td>
<td>0.590420</td>
<td>{'bootstrap': True, 'max_depth': 25, 'min_samp...</td>
<td>MB3_RF</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.48</td>
<td>551.0</td>
<td>0.465409</td>
<td>0.819945</td>
<td>0.593781</td>
<td>{'colsample_bytree': 0.8, 'learning_rate': 0.0...</td>
<td>MB3_XG</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.44</td>
<td>571.0</td>
<td>0.433803</td>
<td>0.853186</td>
<td>0.575163</td>
<td>{'C': 0.1, 'max_iter': 50, 'penalty': 'l2', 's...</td>
<td>MB3_Log_Reg</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="91">
<div class="cell-output cell-output-display" data-execution_count="91">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">threshold</th>
<th data-quarto-table-cell-role="th">score</th>
<th data-quarto-table-cell-role="th">precision</th>
<th data-quarto-table-cell-role="th">recall</th>
<th data-quarto-table-cell-role="th">f1</th>
<th data-quarto-table-cell-role="th">params</th>
<th data-quarto-table-cell-role="th">model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.24</td>
<td>539.0</td>
<td>0.473101</td>
<td>0.828255</td>
<td>0.602216</td>
<td>{'bootstrap': True, 'max_depth': 25, 'min_samp...</td>
<td>MB1_RF</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>0.22</td>
<td>541.0</td>
<td>0.467492</td>
<td>0.836565</td>
<td>0.599801</td>
<td>{'C': 0.1, 'max_iter': 50, 'penalty': 'l2', 's...</td>
<td>MB1_Log_Reg</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>0.44</td>
<td>546.0</td>
<td>0.472266</td>
<td>0.825485</td>
<td>0.600806</td>
<td>{'colsample_bytree': 1.0, 'learning_rate': 0.0...</td>
<td>MB2_XG</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>0.48</td>
<td>546.0</td>
<td>0.472178</td>
<td>0.822715</td>
<td>0.600000</td>
<td>{'C': 1.0, 'max_iter': 50, 'penalty': 'l2', 's...</td>
<td>MB2_Log_Reg</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.48</td>
<td>549.0</td>
<td>0.456193</td>
<td>0.836565</td>
<td>0.590420</td>
<td>{'bootstrap': True, 'max_depth': 25, 'min_samp...</td>
<td>MB3_RF</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.48</td>
<td>551.0</td>
<td>0.465409</td>
<td>0.819945</td>
<td>0.593781</td>
<td>{'colsample_bytree': 0.8, 'learning_rate': 0.0...</td>
<td>MB3_XG</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.42</td>
<td>557.0</td>
<td>0.454955</td>
<td>0.839335</td>
<td>0.590068</td>
<td>{'bootstrap': False, 'max_depth': 25, 'min_sam...</td>
<td>MB2_RF</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.20</td>
<td>558.0</td>
<td>0.449190</td>
<td>0.844875</td>
<td>0.586538</td>
<td>{'colsample_bytree': 0.8, 'learning_rate': 0.0...</td>
<td>MB1_XG</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.44</td>
<td>571.0</td>
<td>0.433803</td>
<td>0.853186</td>
<td>0.575163</td>
<td>{'C': 0.1, 'max_iter': 50, 'penalty': 'l2', 's...</td>
<td>MB3_Log_Reg</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<blockquote class="blockquote">
<p>Analysis of how the models performed:<br> 1.RandomForest performs best with hyperparameter tuning and a lower decision threshold. However, this model performs worst when using SMOTE.<br> 2.LogisticRegression performs worst when using ‘sample weighting’.<br> 3.XGBoost performs best when using SMOTE.<br> 4.It’s important to note that all models produce similar results when using their best parameters and conditions.<br> 5.In my opinion, the greatest impact is achieved by using hyperparameter tuning and decision threshold tuning, rather than using SMOTE and weighting techniques.</p>
</blockquote>
</section>
</section>
<section id="model-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="model-interpretation">Model Interpretation</h2>
<hr>
<p>In this section, I want to show you how to interpret a tree-based model, such as Random Forest, so we can have a better understanding of how the model actually works.</p>
<div class="cell" data-execution_count="92">
<div class="cell-output cell-output-display" data-execution_count="92">
<pre><code>{'bootstrap': True,
 'max_depth': 25,
 'min_samples_leaf': 50,
 'min_samples_split': 50,
 'n_estimators': 250}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="93">
<div class="cell-output cell-output-display" data-execution_count="93">
<style>#sk-container-id-1 {color: black;background-color: white;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>RandomForestClassifier(max_depth=25, min_samples_leaf=50, min_samples_split=50,
                       n_estimators=250)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox" checked=""><label for="sk-estimator-id-1" class="sk-toggleable__label sk-toggleable__label-arrow">RandomForestClassifier</label><div class="sk-toggleable__content"><pre>RandomForestClassifier(max_depth=25, min_samples_leaf=50, min_samples_split=50,
                       n_estimators=250)</pre></div></div></div></div></div>
</div>
</div>
<section id="partial-dependence-plot-pdp-individual-conditional-expectation-ice" class="level3">
<h3 class="anchored" data-anchor-id="partial-dependence-plot-pdp-individual-conditional-expectation-ice">Partial dependence plot (PDP) &amp; Individual conditional expectation (ICE)</h3>
<p>What is ICE? It is a plot that shows how a model makes predictions based on changing the value of one or more features, while keeping the values of other features constant. This provides us with more insights and understanding of how the model treats features to make predictions. ICE works per row (or per customer in this case), and PDP is simply the average of ICE.</p>
<div class="cell" data-execution_count="95">
<div class="cell-output cell-output-stdout">
<pre><code>obtain pred_func from the provided model.</code></pre>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"04674fe01dd14bde8529e5e54c7c1f3f","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-96-output-3.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>The light blue lines represent ICE (Individual Conditional Expectation), and the yellowish blue line represents PDP (Partial Dependence Plot). The X-axis represents MonthlyCharges, while the Y-axis represents the change in prediction probability. At MonthlyCharges of 60.7 USD, you can observe that some customers experience a significant increase in churn probability as the MonthlyCharges increase. However, it is important to note that not all customers have the same response. Some customers are minimally affected, and some may not be affected at all.</p>
</blockquote>
<div class="cell" data-execution_count="96">
<div class="cell-output cell-output-stdout">
<pre><code>obtain pred_func from the provided model.</code></pre>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"64bb89d8bb49434d9ab1fe48bc1e7866","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-97-output-3.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>This is the same plot as above, but I have grouped the ICE into 5 clusters for easier viewing and analysis. You can see that there are some customers who experience a significant increase in churn probability as the MonthlyCharges increase.</p>
</blockquote>
<div class="cell" data-execution_count="97">
<div class="cell-output cell-output-stdout">
<pre><code>obtain pred_func from the provided model.</code></pre>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"eca10db867eb433599ffd371253358d9","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-98-output-3.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>The longer the tenure, the lower the churn probability. However, the effect is not the same for all customers. Some customers are greatly affected, while others are barely affected.</p>
</blockquote>
<div class="cell" data-execution_count="98">
<div class="cell-output cell-output-stdout">
<pre><code>obtain pred_func from the provided model.</code></pre>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"ffe94b164b3748e09a1fae6841a1f865","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-99-output-3.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>The same also goes with Contract. Longer contract means lower churn probability.</p>
</blockquote>
<div class="cell" data-execution_count="99">
<div class="cell-output cell-output-stdout">
<pre><code>obtain pred_func from the provided model.
obtain pred_func from the provided model.
obtain pred_func from the provided model.</code></pre>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"0dc9192bc56345d8acbdf7ccf8a45d40","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"c97c457ef4124592a4f6f0111a0fadf4","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"43323cbd42fb4496af5e0897f0b53d16","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-100-output-5.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Let’s analyze the combination of MonthlyCharges and tenure. We can observe a spike in churn probability for MonthlyCharges ranging from 56.3 USD to 79.2 USD, particularly for customers with a tenure of less than 7 months.</p>
</blockquote>
<div class="cell" data-execution_count="100">
<div class="cell-output cell-output-stdout">
<pre><code>obtain pred_func from the provided model.
obtain pred_func from the provided model.
obtain pred_func from the provided model.</code></pre>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"c89587cb85a4492aa1466083b8e75f04","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"89471e517b3b474d95b343f916b691f2","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"9a6eebc63c2d40d9947bd34b5db4e0bf","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-101-output-5.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>The model produces similar churn probabilities for customers with a combination of a 2-year contract and low tenure compared to those with a month-to-month contract and medium tenure (24-36 months).</p>
</blockquote>
<p>You can see how PDP and ICE plots can be very beneficial in understanding how the model utilizes features to make predictions. In the next section, I will demonstrate how to assess the model’s prediction confidence level.</p>
</section>
<section id="confidence-level-based-on-trees-standard-deviation-and-confidence-interval." class="level3">
<h3 class="anchored" data-anchor-id="confidence-level-based-on-trees-standard-deviation-and-confidence-interval.">Confidence level based on trees’ standard deviation and confidence interval.</h3>
<p>Tree-based models like RandomForest make predictions by using the mean of all the trees’ prediction probabilities. However, instead of solely relying on the mean, we can also calculate the standard deviation. A higher standard deviation indicates lower confidence in the predictions. Additionally, we can utilize confidence intervals, such as 95% or even more extreme at 99%.</p>
<div class="cell" data-execution_count="124">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-104-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Most of predictions have std.deviation under 10%. Let’s calculate confidence interval with 99%.</p>
</blockquote>
<div class="cell" data-execution_count="127">
<div class="cell-output cell-output-display" data-execution_count="127">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Contract</th>
<th data-quarto-table-cell-role="th">tenure</th>
<th data-quarto-table-cell-role="th">Fiber_optic</th>
<th data-quarto-table-cell-role="th">MonthlyCharges</th>
<th data-quarto-table-cell-role="th">FO_LB</th>
<th data-quarto-table-cell-role="th">No_internet</th>
<th data-quarto-table-cell-role="th">avg</th>
<th data-quarto-table-cell-role="th">std_dev</th>
<th data-quarto-table-cell-role="th">CI-99%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">852</td>
<td>2</td>
<td>7</td>
<td>1</td>
<td>94.05</td>
<td>1</td>
<td>0</td>
<td>40.06</td>
<td>25.08</td>
<td>10.199818</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">499</td>
<td>1</td>
<td>58</td>
<td>1</td>
<td>98.70</td>
<td>1</td>
<td>0</td>
<td>41.05</td>
<td>18.24</td>
<td>7.239149</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1186</td>
<td>1</td>
<td>59</td>
<td>1</td>
<td>101.10</td>
<td>1</td>
<td>0</td>
<td>40.37</td>
<td>16.73</td>
<td>6.751699</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1137</td>
<td>1</td>
<td>15</td>
<td>1</td>
<td>96.30</td>
<td>0</td>
<td>0</td>
<td>48.14</td>
<td>19.69</td>
<td>6.663701</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1184</td>
<td>1</td>
<td>10</td>
<td>1</td>
<td>92.50</td>
<td>0</td>
<td>0</td>
<td>48.17</td>
<td>19.12</td>
<td>6.466765</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<blockquote class="blockquote">
<p>Let’s consider the example of row 1. The model predicts a 40% probability of churn for the customer, with a confidence interval of +- 10%. By default, the model’s output indicates that the customer will not churn. However, due to the high confidence interval, it is safer to assume that the customer will churn.</p>
</blockquote>
<p><strong>Checking the standard deviation and confidence interval of the trees is extremely useful, particularly when the cost of ‘False Negative’ is significant and can have severe consequences.</strong></p>
</section>
</section>
</section>
<a class="quarto-notebook-link" id="nblink-1" href="final-project.ipynb.html">Source: final-project.ipynb</a></div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp("https:\/\/ellakaye\.co\.uk");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/EllaKaye/ellakaye.co.uk/issues/new" class="toc-action">Report an issue</a></p></div></div></div></div></footer><script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>